// Untuk mempersingkat dan fokus penelitian adalah penerapan AR, maka tidak menggunakan SQL
import he from "he";
let triviaData = [
  {
    category: "Peredaran Darah",
    type: "multiple",
    difficulty: "easy",
    question: "Bagian jantung di sisi kiri bawah adalah...",
    correct_answer: "Bilik Kiri",
    incorrect_answers: ["Serambi Kanan", "Serambi Kiri", "Bilik Kanan"],
  },
  {
    category: "Peredaran Darah",
    type: "multiple",
    difficulty: "easy",
    question: "Ruang jantung dengan dinding paling tebal adalah...",
    correct_answer: "Bilik Kiri",
    incorrect_answers: ["Serambi Kanan", "Serambi Kiri", "Bilik Kanan"],
  },
  {
    category: "Peredaran Darah",
    type: "multiple",
    difficulty: "easy",
    question: "Pembuluh besar yang keluar dari bagian atas jantung adalah...",
    correct_answer: "Aorta",
    incorrect_answers: ["Vena Pulmonalis", "Katup Bikuspid", "Arteri Pulmonalis"],
  },
  {
    category: "Peredaran Darah",
    type: "multiple",
    difficulty: "easy",
    question: "Serambi kanan berfungsi menerima darah dari...",
    correct_answer: "Seluruh Tubuh",
    incorrect_answers: ["Paru-Paru", "Aorta", "Otak"],
  },
  {
    category: "Peredaran Darah",
    type: "multiple",
    difficulty: "easy",
    question: "Jika bilik kiri tidak berfungsi, maka...",
    correct_answer: "Distribusi darah ke tubuh terganggu",
    incorrect_answers: ["Darah tidak menuju paru-paru", "Napas berhenti", "Paru-paru rusak"],
  },
  {
    category: "Peredaran Darah",
    type: "multiple",
    difficulty: "easy",
    question: "Serambi terletak pada bagian ... jantung",
    correct_answer: "Atas",
    incorrect_answers: ["Bawah", "Belakang", "Samping"],
  },
  {
    category: "Peredaran Darah",
    type: "multiple",
    difficulty: "easy",
    question: "Dinding bilik lebih tebal karena...",
    correct_answer: "Memompa darah lebih kuat",
    incorrect_answers: ["Menyaring udara", "Menghasilkan darah", "Menghasilkan oksigen"],
  },
  {
    category: "Pencernaan",
    type: "multiple",
    difficulty: "easy",
    question: "Organ setelah kerongkongan adalah...",
    correct_answer: "Lambung",
    incorrect_answers: ["Usus Halus", "Hati", "Rektum"],
  },
  {
    category: "Pencernaan",
    type: "multiple",
    difficulty: "easy",
    question: "Organ berbentuk kantong dalam sistem pencernaan adalah...",
    correct_answer: "Lambung",
    incorrect_answers: ["Usus Besar", "Hati", "Pankreas"],
  },
  {
    category: "Pencernaan",
    type: "multiple",
    difficulty: "easy",
    question: "Bagian usus halus yang pertama kali menerima makanan dari lambung adalah...",
    correct_answer: "Duodenum",
    incorrect_answers: ["Rektum", "Ileum", "Jejenum"],
  },
  {
    category: "Pencernaan",
    type: "multiple",
    difficulty: "easy",
    question: "Organ terpanjang dalam sistem pencernaan adalah...",
    correct_answer: "Usus Halus",
    incorrect_answers: ["Usus Besar", "Appendix", "Rektum"],
  },
  {
    category: "Pencernaan",
    type: "multiple",
    difficulty: "easy",
    question: "Jika lambung tidak menghasilkan asam lambung secara normal, maka makanan yang masuk ke tubuh akan...",
    correct_answer: "Tidak hancur dengan baik",
    incorrect_answers: ["Berubah menjadi oksigen", "Lebih cepat dicerna", "Langsung diserap oleh darah"],
  },
  {
    category: "Pencernaan",
    type: "multiple",
    difficulty: "easy",
    question: "Lambung terletak di sebelah ... hati",
    correct_answer: "Kiri",
    incorrect_answers: ["Kanan", "Bawah", "Belakang"],
  },
  {
    category: "Pencernaan",
    type: "multiple",
    difficulty: "easy",
    question: "Usus halus yang panjang berfungsi untuk...",
    correct_answer: "Memperluas penyerapan nutrisi",
    incorrect_answers: ["Memompa darah", "Menghasilkan lemak", "Menyaring udara"],
  },
  {
    category: "Pernapasan",
    type: "multiple",
    difficulty: "hard",
    question: "Organ yang bercabang dua setelah trakea adalah...",
    correct_answer: "Bronkus",
    incorrect_answers: ["Diafragma", "Alveolus", "Bronkiolus"],
  },
  {
    category: "Pernapasan",
    type: "multiple",
    difficulty: "hard",
    question: "Paru-paru terletak di dalam rongga...",
    correct_answer: "Dada",
    incorrect_answers: ["Perut", "Pinggang", "Pinggul"],
  },
  {
    category: "Pernapasan",
    type: "multiple",
    difficulty: "hard",
    question: "Diafragma terletak di bawah...",
    correct_answer: "Paru-paru",
    incorrect_answers: ["Lambung", "Jantung", "Trakea"],
  },
  {
    category: "Pernapasan",
    type: "multiple",
    difficulty: "hard",
    question: "Fungsi utama paru-paru dalam sistem pernapasan adalah...",
    correct_answer: "Tempat pertukaran oksigen dan karbon dioksida",
    incorrect_answers: ["Menyaring racun", "Menghasilkan darah", "Memompa darah"],
  },
  {
    category: "Pernapasan",
    type: "multiple",
    difficulty: "hard",
    question: "Jika satu paru-paru rusak, maka...",
    correct_answer: "Suplai Oksigen berkurang",
    incorrect_answers: ["Oksigen tetap normal", "Jantung rusak", "Darah berhenti"],
  },
  {
    category: "Pernapasan",
    type: "multiple",
    difficulty: "hard",
    question: "Jantung terletak di antara...",
    correct_answer: "Paru-Paru",
    incorrect_answers: ["Lambung", "Ginjal", "Hati"],
  },
];


triviaData = triviaData.map((item) => {
  return {
    ...item,
    question: he.decode(item.question),
    correct_answer: he.decode(item.correct_answer),
    incorrect_answers: item.incorrect_answers.map((incorrect) => he.decode(incorrect)),
  };
});
  
export default triviaData;